name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    run-on: ubuntu-latest
      - name: print greeting
        run: echo "Hello Sarthak"
      - name: print bye
        run: echo "Done - Bye"
