name: Second inline echo workflow
on: workflow_dispatch
jobs:
  runs-on: ubuntu-lastest
  steps:
    - name: Echo botg greetings and Bye
      run: |
          echo "Hi Sarthak"
          echo "Bye Sarthak!!!"
